# Generated by Django 5.2.4 on 2025-08-20 11:33

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('is_answer', models.BooleanField(default=False, verbose_name='is answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='quizes.question', verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('title', models.CharField(verbose_name='title')),
                ('time', models.DurationField(verbose_name='time')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizes.quiz', verbose_name='quiz'),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(verbose_name='time')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('date_time', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizresult', to='quizes.quiz', verbose_name='quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizresult', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('time', models.DurationField(default=datetime.timedelta(0), verbose_name='time')),
                ('rank', models.IntegerField(default=0, verbose_name='rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reportcard', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_choosen', models.BooleanField(default=False, verbose_name='user answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='quizes.option', verbose_name='option')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='quizes.quizresult', verbose_name='quiz rsult')),
            ],
        ),
    ]
