# Generated by Django 5.2.4 on 2025-10-25 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='time'),
        ),
    ]
